config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  get 'home/about'
  get 'home/hello'
  get 'home/youtube'
  get 'home/contact'

#get':controller(/:action(/:id))'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   render('index')
  end
  def about
   @array=[10,20,30,40,50]
   render('about')
  end
  def hello
   redirect_to(:controller=>'home', :action=>'index')
  end
  def youtube
   redirect_to('http://youtube.com')
  end
  def contact
   render('contact')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Basha', root_path, class:"navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">

        <%= link_to "Home", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About us", home_about_path, class:"nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Products
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Two-wheeler</a>
          <a class="dropdown-item" href="#">Three-wheeler</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Others</a>
        </div>
      </li>
      <li>
        <%= link_to "Contact", home_contact_path, class:"nav-link" %>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1> this is about page</h1>
<%= 5+10 %>
=begin
<% var="RubyOnRailsProject" %>
<%= "We are doing #{var}" %>
<% @array.each do |n| %>
<%= n %><br/>
<% end %>
=end

app/views/home/contact.html.erb
<% var="nagurbasha" %>
<%= "sknagurbasha1299@gmail.com #{var}" %>

app/views/home/index.html.erb
<h1>my first project</h1>
<p>Find me in app/views/home/index.html.erb</p>
<a href="/home/about/">About Us from HTML</a><br/>
<a href="/home/about/">home</a><br/>
<a href="/home/details/">details</a><br/>
<a href="/home/contact/">contact</a><br/>
<a href="/home/about/">About Us</a><br/>


<a href="/home/youtube/">you tube from HTML</a><br/>

<%= link_to('About us from RUBY',{:action=>'about'}) %>

<%= link_to('youtube from RUBY',{:action=>'youtube'}) %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

     <title>project1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'home/header' %>
    <div class="container">
    </br>

    <%= yield %>

    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>